FROM python:3.10-alpine

# copy the requirements file into the image
COPY ./requirements-dev.txt /app/requirements-dev.txt

# switch working directory
WORKDIR /app

RUN python3 -m pip install --upgrade pip

# install the dependencies and packages in the requirements file
RUN pip install -r requirements-dev.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python3" ]

CMD ["app.py" ]